api, models: finish adding type hints, make `ConfigurationKey` a proper enum (Bug 1759890)
mozilla-conduit/lando-api pull request #261
Opened 2023-01-17 18:48 UTC by cgsheeh

Finish adding type hints to all modules in `api/` and `models/`.

Type hints for `put` are updated from `int` to `str` to reflect
the correct state in `swagger.yml`.

Add a type alias for configuration values that is an alias to
`bool | int | str`. Also raise at the end of the function to
avoid an accidental `None` return in some edge cases.
Convert `ConfigurationKey` to a proper `Enum` type, add
type hints for it and convert usages of it's underlying `str`
to use the `.value` attribute.

Add `flask_sqlalchemy.BaseQuery` as the return type for
model queries.

2023-01-17 20:21 UTC, zzzeid requested changes

2023-01-17 20:21 UTC, zzzeid commented on landoapi/models/configuration.py
> +ConfigurationValue = Union[bool, int, str]
Something about the name that makes me think this is a value and not a type. Perhaps we could just append "Type" to this.

```suggestion
ConfigurationValueType = Union[bool, int, str]
```

2023-01-17 20:21 UTC, zzzeid commented on landoapi/models/transplant.py
> +    def revisions_query(cls, revisions: list[str]) -> Query:
I think this is technically `flask_sqlalchemy.BaseQuery`.

2023-01-18 15:48 UTC, cgsheeh commented
Added some changes around `ConfigurationKey` to this patch FYI.

2023-01-19 20:46 UTC, zzzeid requested changes
I think the enum change no longer matches with the title of this commit, it should go in its own commit or the title should be changed.

2023-01-20 16:29 UTC, cgsheeh commented
@zzzeid I updated the title, let me know if this is better or if you have a suggestion otherwise.

2023-01-20 18:32 UTC, zzzeid approved these changes
I would shorten it to something like:
`api, models: add more type hints, use enum (bug 1759890)`

And put the rest in the message.

2023-01-20 18:37 UTC, merged